config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip:[:passwords],controllers:{
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  devise_for :admin, skip:[:passwords,:registrations],controllers:{
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to: 'homes#top'
  
  namespace :admin do
   root to: 'homes#top'
   resources :genres, except: [:show, :destroy, :new]
   resources :items, except: [:destroy]
   resources :users, except: [:new, :create, :destroy]
   resources :orders
   resources :order_details, only:[:update]
  end  
  
  namespace :public do
   resources :users,except: [:new, :index]
   get 'users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
   patch 'users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'
   get 'orders/thanks', to: 'orders#thanks'
   post 'orders/confirm' => 'orders#confirm'
   resources :orders
   resources :addresses,except: [:new, :show]
   resources :items, only: [:index, :show]
   resources :cart_items, except: [:show, :new, :edit] 
   delete 'cart_items' => 'cart_items#destroy_all'
  end  
  
end

app/models/address.rb
class Address < ApplicationRecord
    
    belongs_to :user
    
    validates :postal_code, presence: true
    validates :address, presence: true
    validates :name, presence: true
    
    def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
    end 
    
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord


 belongs_to :user
 belongs_to :item
 
 def with_tax_price
   (price*1.1).floor
 end
 
  #小計
 def subtotal
     item.with_tax_price*amount
 end
    
end

app/models/genre.rb
class Genre < ApplicationRecord
    
    has_many :items,dependent: :destroy
    
    validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  
  
 has_many :cart_items, dependent: :destroy 
  
    
 belongs_to :genre
 has_one_attached :image
 
  
  validates :name, presence: true
  validates :price, presence: true

def with_tax_price
   (price * 1.1).floor
end

end

app/models/order.rb
class Order < ApplicationRecord
    
     has_many :order_details, dependent: :destroy
    belongs_to :user
    
    validates :postal_code, presence: true
    validates :address, presence: true
    validates :name, presence: true
    validates :way_of_paying, presence: true
    
    def with_tax_price
   (price*1.1).floor
    end
    
    enum way_of_paying: { credit_card:0, transfer:1 }
    
    enum recieve_status:{ not_yet:0, waiting:1, working:2, complete:3}
    
    


end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    
    belongs_to :order
    belongs_to :item
    
    
   
    
    
     def subtotal
     item.with_tax_price*amount
     end
     
     
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
   validates :last_name, presence: true
   validates :first_name, presence: true
   validates :last_name_kana, presence: true
   validates :first_name_kana, presence: true
   validates :postal_code, presence: true
   validates :telephone_number, presence: true
   validates :address, presence: true
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    
  def new
    @item = Item.new
    @genres = Genre.all
  end 
  
  def create
    @item = Item.new(item_params)
    if @item.save
     redirect_to admin_item_path(@item.id), notice: "新商品登録完了！"
    else
     frash.now[:alert] = "もう一度入力し直してください"
     render "index"
    end
 
  end
  
  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item.id)
    
  end
  
  
  def index
    @items = Item.all
  end
  
  def show
    @item = Item.find(params[:id])
  end
  
  def edit
    @genres = Genre.all
    @item = Item.find(params[:id])
  end
  
  
  private
  
  def item_params
    params.require(:item).permit(:name, :introduction, :price, :genre_id, :is_active, :image)
  end
  
  
  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
    
  before_action :authenticate_admin!

  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
   
  end
  
  
  private

  def order_params
    params.require(:order).permit(:order_status)
  end
    
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    
   def index    
     @users = User.all
   end
   
   def show
     @user = User.find(params[:id])
   end 
  
   def edit
     @user = User.find(params[:id])
   end 
  
    def update
     @user = User.find(params[:id])
     if @user.update(user_params)
        redirect_to admin_user_path(@user)
     else
        render :edit
     end   
    end
  
  private
   
   def user_params
     params.require(:user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
   end 


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?   
    
    protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/orders/index.html.erb
<div class="p-5 ml-10 mr-10 w-80">
  <h2><span class="bg-gray">注文履歴一覧</span></h2>
  <table class="table">
    <thead class="bg-gray">
      <tr>
        <th>購入日時</th>
        <th>購入者</th>
        <th>注文個数</th>
        <th>注文ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= link_to order.created_at.strftime("%Y/%m/%d"),admin_order_path(order.id) %></td>
          <td><%= order.user.first_name+order.user.last_name %></td>
          <td><%= order.order_details.sum(:amount) %></td>
          <td><%= Order.recieve_statuses_i18n[order.recieve_status] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/orders/show.html.erb
<div calss="container">
    <div class="row">
        <div class="col-md-6 offset-md-1">
          <h2 class="my-4">注文履歴詳細</h2>
        </div>
    </div>
</div>
<div class="col-6">
  <table calss="order-customer">
    <tr>
      <th>購入者</th>
      <td><%= @order.name %></td>
    </tr>
    <tr>
      <th>注文日</th>
      <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
    </tr>
    <tr>
      <th>配送先</th>
      <td><%= @order.address %></td>
    </tr>
    <tr>
      <th>支払方法</th>
      <td><%= Order.way_of_payings_i18n[@order.way_of_paying] %></td>
    </tr>
    <tr>
      <%= form_with(model: @order, url:admin_order_path, local: true) do |f| %>
      <th>注文ステータス</th>
      <td>
        
        <%= f.select :recieve_status, Order.recieve_statuses.keys.map{|k| [I18n.t("enums.order.recieve_status.#{k}"),k]} ,{},{class: 'form-control'}  %>
        <%= f.submit "更新", class:"btn btn-success" %>
      </td>
      <% end %>
    </tr>
   </table>
  </div>
  <div class="row">
   <div class="col-7">
     <table class="table table-bordered">
       <thead>
         <th>商品名</th>
         <th>単価</th>
         <th>数量</th>
         <th>小計</th>
         <th>製作ステータス</th>
       </thead>
       <tbody>
         <% @order.order_details.each do |order_detail| %>
         <tr>
           <td><%= order_detail. item.name %></td>
           <td><%= (order_detail.purchase_price).to_s(:delimited) %> 円</td>
           <td><%= (order_detail.amount).to_s(:delimited) %> 個</td>
           <td><%= (order_detail.purchase_price*order_detail.amount).to_s(:delimited) %></td>
         </tr>  
             <div>
               
               
               <%= form_with model: order_detail, url: admin_order_detail_path(order_detail.id),method: :patch do |f| %>
                 <%= f.select :production_status, options_for_select([['着手不可'],['製作待ち'],['製作中'],['製作完了']],{:selected => order_detail.production_status}) %>
                 <%= f.submit "更新", class:"btn btn-success" %>
               <% end %>  
             </div>
           </td>  
         </tr>
         <% end %>
        </tbody>
      </table>
     </div>
     <div calss="col-4">
       <table>
         <tr>
           <th>商品合計</th>
           <td><%= (@order.billing_amount - @order.shipping_fee) %>円</td>
         </tr>
         <tr>
           <th>送料</th>
           <td><%= @order.shipping_fee %>円</td>
         </tr>  
         <tr>
            <th>請求金額合計</th> 
            <td><%= @order.billing_amount %>円</td>
         </tr>     
       </table>
     </div>
    </div>