config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip:[:passwords],controllers:{
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  devise_for :admin, skip:[:passwords,:registrations],controllers:{
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to: 'homes#top'
  
  namespace :admin do
   root to: 'homes#top'
   resources :genres, except: [:show, :destroy, :new]
   resources :items, except: [:destroy]
   resources :users, except: [:new, :create, :destroy]
   resources :orders
   resources :order_details, only:[:update]
  end  
  
  namespace :public do
   resources :users,except: [:new, :index]
   get 'users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
   patch 'users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'
   get 'orders/thanks', to: 'orders#thanks'
   post 'orders/confirm' => 'orders#confirm'
   resources :orders
   resources :addresses,except: [:new, :show]
   resources :items, only: [:index, :show]
   resources :cart_items, except: [:show, :new, :edit] 
   delete 'cart_items' => 'cart_items#destroy_all'
  end  
  
end

app/models/address.rb
class Address < ApplicationRecord
    
    belongs_to :user
    
    validates :postal_code, presence: true
    validates :address, presence: true
    validates :name, presence: true
    
    def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
    end 
    
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord


 belongs_to :user
 belongs_to :item
 
 def with_tax_price
   (price*1.1).floor
 end
 
  #小計
 def subtotal
     item.with_tax_price*amount
 end
    
end

app/models/genre.rb
class Genre < ApplicationRecord
    
    has_many :items,dependent: :destroy
    
    validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  
  
 has_many :cart_items, dependent: :destroy 
  
    
 belongs_to :genre
 has_one_attached :image
 
  
  validates :name, presence: true
  validates :price, presence: true

def with_tax_price
   (price * 1.1).floor
end

end

app/models/order.rb
class Order < ApplicationRecord
    
     has_many :order_details, dependent: :destroy
    belongs_to :user
    
    validates :postal_code, presence: true
    validates :address, presence: true
    validates :name, presence: true
    validates :way_of_paying, presence: true
    
    def with_tax_price
   (price*1.1).floor
    end
    
    enum way_of_paying: { credit_card:0, transfer:1 }
    
    enum recieve_status:{ not_yet:0, waiting:1, working:2, complete:3}
    
    


end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    
    belongs_to :order
    belongs_to :item
    
    
   
    
    
     def subtotal
     item.with_tax_price*amount
     end
     
     
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
   validates :last_name, presence: true
   validates :first_name, presence: true
   validates :last_name_kana, presence: true
   validates :first_name_kana, presence: true
   validates :postal_code, presence: true
   validates :telephone_number, presence: true
   validates :address, presence: true
  
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
    
    def index
      @genre = Genre.new
      @genres = Genre.all
    end 
    
    def create
      @genre = Genre.new(genre_params)
     if @genre.save
      redirect_to admin_genres_path
     else
      flash[:alert]= "もう一度入力してね"
      @genres = Genre.all
      render:index
     end
     
    end
    
    def edit
      @genre = Genre.find(params[:id])
    end  
    
    def update
      @genre = Genre.find(params[:id])
     if @genre.update(genre_params)
      redirect_to admin_genres_path, notice: "ジャンルを編集したよ。"
     else
      flash[:alert] = "もう一度入力してね。"
      render :edit
     end
    end
    
    private
       
     def genre_params
      params.require(:genre).permit(:name)
     end
    
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    
  def new
    @item = Item.new
    @genres = Genre.all
  end 
  
  def create
    @item = Item.new(item_params)
    if @item.save
     redirect_to admin_item_path(@item.id), notice: "新商品登録完了！"
    else
     frash.now[:alert] = "もう一度入力し直してください"
     render "index"
    end
 
  end
  
  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item.id)
    
  end
  
  
  def index
    @items = Item.all
  end
  
  def show
    @item = Item.find(params[:id])
  end
  
  def edit
    @genres = Genre.all
    @item = Item.find(params[:id])
  end
  
  
  private
  
  def item_params
    params.require(:item).permit(:name, :introduction, :price, :genre_id, :is_active, :image)
  end
  
  
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    
   def index    
     @users = User.all
   end
   
   def show
     @user = User.find(params[:id])
   end 
  
   def edit
     @user = User.find(params[:id])
   end 
  
    def update
     @user = User.find(params[:id])
     if @user.update(user_params)
        redirect_to admin_user_path(@user)
     else
        render :edit
     end   
    end
  
  private
   
   def user_params
     params.require(:user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
   end 


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?   
    
    protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/genres/edit.html.erb
<main>
  <div class="container">
     <h3>ジャンル編集<i class="fas fa-pen-nib"></i></h3>
  </div>
  
  <br>
  
  <div class="row">
    <div calss="col-2">
        ジャンル名
    </div>
    
    
    <%= form_with model:@genre,url: admin_genre_path(@genre),local:true do |f| %>
    <div calss="d-flex flex-row form-group">
      <div>
        <%= f.text_field :name,autofocus: true, id:"inputName", :class=> 'form-control' %>
      </div>
      
      <div>
        <%= f.submit "変更を保存" ,class: 'btn btn-success offset-md-2' %>
      </div>
    </div>
    <% end %>
    
    
   </div>
  </div>
 </main>
      

app/views/admin/genres/index.html.erb
<main>
    <div class="container">
        <div class="row">
          <h3><span calss="heading">ジャンル一覧・追加<i class="fas fa-utensils"></i></span></h3>
        </div>
        
        <br> 
        
        
        <div class="row">
          <div class="col-2">
              ジャンル名
          </div>
          
          <%= form_with model:@genre,url: admin_genres_path, local:true do |f| %>
          <div class="d-flex flex-row form-group">
             <div>
               <%= f.text_field :name, :class => 'form-control' %>
             </div>
             
             <div>
               <%= f.submit "新規登録", class: 'btn btn-success offset-md2' %>
             </div>
          </div>
          <% end %>
         </div>
         
         <br>
         
         
         <div class="row">
           <div class="col-md-8">
              <table class="genres">
                <tr>
                 <th class="col-md-8">ジャンル</th>
                 <th class="col-md-4"></th>
                </tr>
                <% @genres.each do |genre| %>
                <tr>
                 <td><%= genre.name %></td>
                 <td>
                    <%= link_to edit_admin_genre_path(genre.id) do %>
                      <button type="button" class="btn btn-success">編集する</button>
                    <% end %>
                 </td>
                </tr>
                <% end %>
             </table>
            </div>
           </div>
          </div>
         </main>

app/views/admin/items/edit.html.erb
<div class="container">
  <h3>商品編集</h3>
  <div class="row">
      
    <%= form_with model: @item, url: admin_item_path(@item.id), local: true do |f| %>
      <table>
         <tr>
           <th>商品画像</th>
           <td><%= f.file_field :image,accept: "image/*" %></td>
         </tr>
         <tr><td>&nbsp;</td></tr>
         <tr>
           <th>商品名</th>
           <td><%= f.text_field :name %></td>
         </tr>
         <tr><td>&nbsp;</td></tr>
         <tr>
           <th>商品説明</th>
           <td><%= f.text_area :introduction %></td>
         </tr>
         <tr><td>&nbsp;</td></tr>
         <tr>
           <th>ジャンル</th>
           <td><%= f.collection_select(:genre_id, @genres, :id, :name, prompt: "選択してください") %>
         </tr>
         <tr><td>&nbsp;</td></tr>
         <tr>
           <th>税抜価格</th>
           <td><%= f.text_field :price %>円</td>
         </tr>
         <tr><td>&nbsp;</td></tr>
         <tr>
           <th>販売ステータス</th>
           <td>
              <%= f.radio_button :is_active, :true %>
              <%= f.label :is_active, "販売中" %>
              <%= f.radio_button :is_active, :false %>
              <%= f.label :is_active, "販売停止中" %>
           </td>
         </tr>
       </table>
       <br>
       <%= f.submit "変更を保存", class: 'btn btn-primary' %>
     <% end %>
  </div>
 </div>

app/views/admin/items/index.html.erb
<div class="container">
    <div class="row">
      <div class="col-md-2">
         <h3>商品一覧</h3>
      </div>
      
      
      
      <div class="col-md-1 offset-md-9">
          <%= link_to new_admin_item_path do %>
           <h3><i class="fas fa-plus-circle"></i></h3>
          <% end %>
      </div>
    </div> 
       
       
      <div class="row">
          <table class="table cart_items">
            <tr>
              <th class="col-md-1">商品ID</th>
              <th class="col-md-3">商品名</th>
              <th class="col-md-2">税抜価格</th>
              <th class="col-md-2">ジャンル</th>
              <th class="col-md-2">ステータス</th>
            </tr>
            <% @items.each do |item| %>
            <tr>
              <td class="col-md-1"><%= item.id %></td>
              <td class="col-md-3"><%= link_to item.name, admin_item_path(item.id) %></td>
              <td class="col-md-2"><%= item.price %></td>
              <td class="col-md-2"><%= item.genre.name %></td>
              <td class="col-md-2"><%= item.is_active ? "販売中" : "販売停止中" %></td>
            </tr>
            <% end %>
          </table>
         </div>
        </div> 

app/views/admin/items/new.html.erb
<main>
<div class="container">
  <h3>商品新規登録</h3>
  <div class="row">
      
     
     <%= form_with model:@item, url:admin_items_path,local: true do |f| %>
     <div class="col">
         
     </div>
       <table class="admin_items">
        <tr>
          <th>商品画像</th>
          <td><%= f.file_field:image,accept: "image/*" %></td>
        </tr>
        <tr>
          <th>商品名</th>
          <td><%= f.text_field:name %></td>
        </tr>
        <tr>
          <th>商品説明</th>
          <td><%= f.text_area:introduction %></td>
        </tr>
        <tr>
          <th>ジャンル</th>
          <td><%= f.collection_select(:genre_id, @genres, :id, :name , prompt: "選択してください") %></td>
        </tr>
        <tr>
          <th>税抜価格</th>
          <td><%= f.text_field:price %>円</td>
        </tr>
        <tr>
          <th>販売ステータス</th>
          <td class="col-md-3">
            <%= f.radio_button :is_active, :true %>
            <%= f.label :is_active, "販売中" %>
            <%= f.radio_button :is_active, :false %>
            <%= f.label :is_active, "販売停止中" %>
          </td>  
        </tr>
       </table>
       <br>
       <%= f.submit "新規登録" , class: 'btn btn-primary' %>
       <% end %>
      </div>
     </div>
</main>          

app/views/admin/items/show.html.erb
<div class="container">
  <h3>商品詳細</h3>
  <div class="row">
    <div class="col-md-4">
     <% if @item.image.attached? %>    
     <%= image_tag @item.image, size: "200x200" %>
     <% end %>
    </div>
    <div class="col-md-5">
      <table class="table cart_items">
        <tr>
          <th>商品</th>
          <td><%= @item.name %></td>
        </tr>
        <tr>
          <th>商品説明</th>
          <td><%= @item.introduction %></td>
        </tr>  
        <tr>
          <th>ジャンル</th>
          <td><%= @item.genre.name %></td>
        </tr>
        <tr>
          <th>税込価格<br> （税抜価格）</th>
          <td><%= @item.with_tax_price.to_s(:delimited) %> (<%= @item.price.to_s(:delimited) %>) 円</td> 
        </tr>
        <tr>
          <th>販売ステータス</th>
          <td><%= @item.is_active ? "販売中" : "販売停止中" %></td>
        </tr>
      </table>
      <br>
       <%= link_to edit_admin_item_path(@item.id) do %>
        <button type="button" class="btn btn-success">
          編集する
         </button>
       <% end %>
      </div>
     </div>
    </div>

app/views/admin/users/edit.html.erb
<div class="container">
    <div class="row">
      <h3><%= @user.last_name %><%= @user.first_name %>さんの会員情報編集</h3>
    </div>
    
    
    <%= form_with model:@user, url: admin_user_path, method: :PATCH, local:true do |f| %>
    <div class="col">
        
      
    </div>
    <div class="form-group row">
        <div class="col-md-3">会員ID</div>
        <div class="col-md-2"><%= @user.id %></div>
    </div>
    <div class="form-group row">
        <%= f.label :氏名, class: "col-md-3" %>
        <%= f.text_field :last_name, class: "col-md-2 form-control" %>
        <%= f.text_field :first_name, class: "col-md-2 form-control ml-3" %>
    </div>
    <div class="form-group row"> 
        <%= f.label :フリガナ, class: "col-md-3" %>
        <%= f.text_field :last_name_kana, class: "col-md-2 form-control" %>
        <%= f.text_field :first_name_kana, class: "col-md-2 form-control ml-3" %>
    </div>
    <div class="form-group row">
        <%= f.label :郵便番号, class: "col-md-3" %>
        <%= f.text_field :postal_code, class: "col-md-5 form-control" %>
    </div>
    <div calss="form-group row">
        <%= f.label :住所, class: "col-md-3" %>
        <%= f.text_field :address, class: "col-md-5 form-cntrol" %>
    </div>
    <div class="form-group row">
        <%= f.label :電話番号, class: "col-md-3" %>
        <%= f.text_field :telephone_number, class: "col-md-5 form-control" %>
    </div>    
    <div class="form-group row">
        <%= f.label :メールアドレス, class: "col-md-3" %>
        <%= f.email_field :email, class: "col-md-5 form-control" %>
    </div>
    <div class="form-group row">
        <%= f.label :会員ステータス, class: "col-md-3" %>
        <label><%= f.radio_button :is_deleted?, false, checked: true %>有効</label>
        <label class="ml-3"><%= f.radio_button :is_deleted, true %>退会</label>
    </div>
      
      
    <div class="form-group row">
        <%= f.submit "変更を保存", class: "btn btn-success col-md-2 offset-3" %>
    </div>
   <% end %>
   </div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row">
   <h3>会員一覧<i class="fas fa-users"></i></h3>
  </div>

<table class="table cart_items">
  <tr>
    <th>会員ID</th>
    <th>氏名</th>
    <th>メールアドレス</th>
    <th>ステータス</th>
  </tr>
  <% @users.each do |user| %>
  <tr>
    <td><%= user.id %></td>
    <td>
      <%= link_to admin_user_path(user) do %>
        <%= user.last_name %><%= user.first_name %>
      <% end %>
    </td>
    <td><%= user.email %></td>
    <% if user.is_deleted == false %>
      <td>会員</td>
    <% else %>
      <td>退会済み</td>
     <% end %>
  </tr>
  <% end %>
 </table>

</div>

app/views/admin/users/show.html.erb
<div class="container">
    <div class="row">
      <h3><%= @user.last_name %><%= @user.first_name %>さんの会員情報詳細</h3>
    </div>
    
   <div class="row">
    <div class="col-md-12">
        <table class="table cart_items">
          <tr>
            <th style="width: 30%">会員ID</th>
            <td style="width: 70%"><%= @user.id %></td>
          </tr>
          <tr>
             <th>氏名</th>
             <td><%= @user.last_name %><%= @user.first_name %></td>
          </tr>
          <tr>
             <th>フリガナ</th>
             <td><%= @user.last_name_kana %><%= @user.first_name_kana %></td>
          </tr>
          <tr>
             <th>郵便番号</th>
             <td><%= @user.postal_code %></td>
          </tr>
          <tr>
             <th>住所</th>
             <td><%= @user.address %></td>
          </tr>
          <tr>
             <th>電話番号</th>
             <td><%= @user.telephone_number %></td>
          </tr>
          <tr>
             <th>メールアドレス</th>
             <td><%= @user.email %></td>
          </tr>
          <tr>
             <th>会員ステータス</th>
             <% if @user.is_deleted == false %>
              <td>有効</td>
             <% else %>
              <td>退会</td>
             <% end %>
          </tr>
         </table>
        </div>
       </div>
       
        
 <div class="row">
    <div class="col-md-5 clearfix">
        
     <div class="float-right"><%= link_to "編集する", edit_admin_user_path(@user), class: "btn btn-success" %></div>      
    </div>
    <div class="col-md-7">
      <%= link_to "注文履歴一覧を見る", admin_orders_path, class: "btn btn-primary" %>    
    </div>
 </div>
 
</div>