config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip:[:passwords],controllers:{
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  devise_for :admin, skip:[:passwords,:registrations],controllers:{
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to: 'homes#top'
  
  namespace :admin do
   root to: 'homes#top'
   resources :genres, except: [:show, :destroy, :new]
   resources :items, except: [:destroy]
   resources :users, except: [:new, :create, :destroy]
   resources :orders
   resources :order_details, only:[:update]
  end  
  
  namespace :public do
   resources :users,except: [:new, :index]
   get 'users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
   patch 'users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'
   get 'orders/thanks', to: 'orders#thanks'
   post 'orders/confirm' => 'orders#confirm'
   resources :orders
   resources :addresses,except: [:new, :show]
   resources :items, only: [:index, :show]
   resources :cart_items, except: [:show, :new, :edit] 
   delete 'cart_items' => 'cart_items#destroy_all'
  end  
  
end

app/models/address.rb
class Address < ApplicationRecord
    
    belongs_to :user
    
    validates :postal_code, presence: true
    validates :address, presence: true
    validates :name, presence: true
    
    def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
    end 
    
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord


 belongs_to :user
 belongs_to :item
 
 def with_tax_price
   (price*1.1).floor
 end
 
  #小計
 def subtotal
     item.with_tax_price*amount
 end
    
end

app/models/genre.rb
class Genre < ApplicationRecord
    
    has_many :items,dependent: :destroy
    
    validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  
  
 has_many :cart_items, dependent: :destroy 
  
    
 belongs_to :genre
 has_one_attached :image
 
  
  validates :name, presence: true
  validates :price, presence: true

def with_tax_price
   (price * 1.1).floor
end

end

app/models/order.rb
class Order < ApplicationRecord
    
     has_many :order_details, dependent: :destroy
    belongs_to :user
    
    validates :postal_code, presence: true
    validates :address, presence: true
    validates :name, presence: true
    validates :way_of_paying, presence: true
    
    def with_tax_price
   (price*1.1).floor
    end
    
    enum way_of_paying: { credit_card:0, transfer:1 }
    
    enum recieve_status:{ not_yet:0, waiting:1, working:2, complete:3}
    
    


end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    
    belongs_to :order
    belongs_to :item
    
    
   
    
    
     def subtotal
     item.with_tax_price*amount
     end
     
     
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
   validates :last_name, presence: true
   validates :first_name, presence: true
   validates :last_name_kana, presence: true
   validates :first_name_kana, presence: true
   validates :postal_code, presence: true
   validates :telephone_number, presence: true
   validates :address, presence: true
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    
  def new
    @item = Item.new
    @genres = Genre.all
  end 
  
  def create
    @item = Item.new(item_params)
    if @item.save
     redirect_to admin_item_path(@item.id), notice: "新商品登録完了！"
    else
     frash.now[:alert] = "もう一度入力し直してください"
     render "index"
    end
 
  end
  
  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item.id)
    
  end
  
  
  def index
    @items = Item.all
  end
  
  def show
    @item = Item.find(params[:id])
  end
  
  def edit
    @genres = Genre.all
    @item = Item.find(params[:id])
  end
  
  
  private
  
  def item_params
    params.require(:item).permit(:name, :introduction, :price, :genre_id, :is_active, :image)
  end
  
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?   
    
    protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IbarakiCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/cbde064e64.js" crossorigin="anonymous"></script>
  </head>
  
  <body class="d-flex flex-column vh-100">
  <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class-"container">
          <a class="navbar-brand p-3" href="/"> <%= image_tag 'kitty cake.jpg', :size =>'200x200' %></a>
          <a class="navbar-brand p-3" href="/"> <%= image_tag 'maron.jpg', :size =>'200x200' %></a>
          <a class="navbar-brand p-3" href="/"> <%= image_tag 'cheese.jpg', :size =>'200x200' %></a>
          <%=link_to root_path, class: 'nav-link text-blue' do %>
          <h1><strong><i class="fas fa-birthday-cake"></i>Ibaraki Cake<i class="fas fa-birthday-cake"></i></strong></h1>
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
         </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
      
        <% if user_signed_in? %>
              <p>ようこそ<%= current_user.last_name %>さん！</p>
            <% end %>
    <ul class="navbar-nav ml-auto">
       <% if user_signed_in? %>
       <li class="navbar-link"><%= link_to "商品一覧", public_items_path, class: "btn btn-outline-dark" %></li>
       <li class="navbar-link"><%= link_to "カート内商品", public_cart_items_path, class: "btn btn-outline-dark" %></li>
       <li class="navbar-link"><%= link_to "マイページ", public_user_path(current_user), class: "btn btn-outline-dark" %></li>
       <li class="navbar-link"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-outline-dark" %></li>
       <% elsif admin_signed_in? %>
       <li class="navbar-link"><%= link_to "商品一覧", admin_items_path, class: "btn btn-outline-dark" %></li>
       <li class="navbar-link"><%= link_to "会員一覧", admin_users_path, class: "btn btn-outline-dark" %></li>
       <li class="navbar-link"><%= link_to "ジャンル一覧", admin_genres_path, class: "btn btn-outline-dark" %></li>
       <li class="navbar-link"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-dark" %></li>
      <% else %>
       
       
       <li class="navbar-link"><%= link_to "新規登録", new_user_registration_path, class: "btn btn-outline-dark" %></li>
       <li class="navbar-link"><%= link_to "ログイン", new_user_session_path, class: "btn btn-outline-dark" %></li>
       <li class="navbar-link"><%= link_to "管理者ログイン", new_admin_session_path, class: "btn btn-outline-dark" %></li>
      <% end %>
    </ul>
        
      </div>
      </div>
      </nav>
      </header>
      <main class="mb-auto">
       <%= yield %>
       </main>

   <footer class="bg-dark text-white">
      <div class="container">
        <p>©茨城ケーキ</p>
      </div>
  </footer>
  </body>

</html>